### PR TITLE
[chrome] fix occasional long timeouts and loss of websocket connection due to heavy throttling of background trabs

### LINKED ISSUE #113: investigate ws connection losses
after a while, the browser console shows many 

```
 ￼Bbp0PqUz.js:49 [fetchIncogniteeNotes] error Error: No response received from RPC endpoint in 60s
17
￼Cg5A4fbM.js:14 Error: No response received from RPC endpoint in 60s
    at ji.__internal__timeoutHandlers (￼CkpypJWy.js:100:19166)
    at ￼CkpypJWy.js:100:21381
￼bQho2aB0.js:1 2025-01-30 13:43:10          API-WS: disconnected from ￼wss://scv1.asset-hub-polkadot.api.incognitee.io:443: 1006:: Abnormal Closure
2
￼Bbp0PqUz.js:49 [fetchIncogniteeNotes] error Error: disconnected from ￼wss://scv1.asset-hub-polkadot.api.incognitee.io:443: 1006:: Abnormal Closure
2
￼Cg5A4fbM.js:14 Error: disconnected from ￼wss://scv1.asset-hub-polkadot.api.incognitee.io:443: 1006:: Abnormal Closure
    at WebSocket.__internal__onSocketClose (￼CkpypJWy.js:100:15983)
```

we also see errors on the worker side logs:

```
[2025-01-30T10:46:28.083721Z ERROR itc_tls_websocket_server::stream_state] Web-socket handshake failed: Protocol(MissingConnectionUpgradeHeader)
[2025-01-30T08:34:54.948795Z ERROR itc_tls_websocket_server::connection] cannot process TLS packet(s), closing connection: CorruptMessage
```

### LINKED ISSUE #121: [chrome] heavy throtting of chrome closes websocket connection after 5-7 minutes of inactivity
To be precise, the websocket is not closed, but the timers that poll information are throttled to run less than once per minute. In this case, there is a websocket timeout, which closes the websocket.

See chrome issue: https://developer.chrome.com/blog/timer-throttling-in-chrome-88/

There are several options to work around this. The primary objective of throttling in chrome was to motivate better design patterns that are not affected by it.

### PR DESCRIPTION
**Pull request by clangenb**
We detect now if the browser goes into background, and stop polling the getters in this case. Additionally, we manually close the websocket after 20 seconds (this prevents unexpected closed errors). When we come into foreground again, we open a new websocket connection with the worker's new `reconnect` method. Note: if we were connected once, and lose the connection, we have to call `reconnect` on the `worker` instead of `connect`, connect will fail (this is a bit confusing to me, but it seems to be the standard of websockets).

* Closes #121
* Closes #113 

Issues:
- I don't understand yet how to stop polling the notes when in the background (as I don't understand vue yet)
- Under some circumstances (e.g. low user interaction), chrome might throttle even while being in the foreground. We could take some additional measures to detect that too. However, I made the practical approach now, and just put some connection checks, and reconnect as a safety measure in case we still lose a connection sometimes. So we might still see occasional websocket closed errors, but we should recover immediately from it.
- In the future, we should probably make the worker have automatic websocket disconnect detection and establish reconnection, so that the front-end does not have to care about that, see https://github.com/encointer/encointer-js/issues/129

### CODE REVIEW

File: pages/index.vue [hunk 1]
```diff
@@ -701,7 +724,79 @@ watch(pollCounter, async () => {
...
+  }
+
+  await fetchWorkerData();
+
+  if (isPolling.value) {
+    // Schedule the next polling.
+    pollingTimeout = setTimeout(pollWorker, pollingInterval);
+  }
+}
+
```
Comment (clangenb) [inline pages/index.vue:752]: Apparently, polling with timeouts is less affected by throttling than vue's `useInterval`.

**Review by brenzi — APPROVED** [review]
great improvement
